// <auto-generated />
namespace KyleTanczos.TestKyle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeAddViewedUserlisttostation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeAddViewedUserlisttostation));
        
        string IMigrationMetadata.Id
        {
            get { return "201604112246327_remove-AddViewedUserlisttostation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
