// <auto-generated />
namespace KyleTanczos.TestKyle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBlobFiletoUserandOrgUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBlobFiletoUserandOrgUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201603232119171_Add BlobFile to User and OrgUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
